# Generated by Django 4.0.4 on 2022-05-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsitem',
            name='destination',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contentsitem',
            name='color',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='contentsitem',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contentsitem',
            name='position',
            field=models.CharField(default='', max_length=10),
        ),
    ]
