# Generated by Django 4.0.4 on 2022-05-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0002_contentsitem_destination_alter_contentsitem_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsitem',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
