# Generated by Django 4.0.4 on 2022-06-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0006_remove_contentsitem_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsitem',
            name='style',
            field=models.CharField(default='', max_length=100),
        ),
    ]
