# Generated by Django 4.0.4 on 2022-07-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0008_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='img',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
