# Generated by Django 4.0.4 on 2022-07-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0009_alter_highlight_description_alter_highlight_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highlight',
            old_name='img',
            new_name='imgLink',
        ),
        migrations.AddField(
            model_name='highlight',
            name='style',
            field=models.CharField(default='', max_length=100),
        ),
    ]
