# Generated by Django 4.0.4 on 2022-07-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0011_alter_highlight_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='style',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
