# Generated by Django 4.0.4 on 2022-06-12 23:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps_investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investment',
            name='business',
            field=models.ManyToManyField(to='apps_businesses.business'),
        ),
        migrations.AddField(
            model_name='investment',
            name='period',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='investment',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
