# Generated by Django 4.0.4 on 2022-05-30 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0003_contentsitem_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentsitem',
            old_name='color',
            new_name='style',
        ),
    ]
