# Generated by Django 4.0.4 on 2022-06-06 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0005_alter_contentsitem_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentsitem',
            name='position',
        ),
        migrations.RemoveField(
            model_name='contentsitem',
            name='style',
        ),
    ]
