# Generated by Django 4.0.4 on 2022-06-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('number', models.IntegerField(default=1)),
                ('description', models.CharField(default='', max_length=100)),
                ('growth_rate', models.IntegerField(default=100)),
                ('locations', models.CharField(max_length=100)),
            ],
        ),
    ]
