# Generated by Django 4.0.4 on 2022-08-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_businesses', '0003_remove_job_pay_job_description_job_num_openings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='num_openings',
            new_name='openings',
        ),
        migrations.AddField(
            model_name='job',
            name='period',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='qualifications',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
