# Generated by Django 4.0.4 on 2022-06-06 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_users', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
